#!/bin/bash

#
# This file is part of timedilation.
#
# Based on mutrace shell script: Copyright 2009 Lennart Poettering
#

if ! TEMP=`getopt -o +n:h --long multiple:,help -n timedilation -- "$@"` ; then
    exit 1
fi

eval set -- "$TEMP"

while : ; do
  case $1 in
    -n|--multiple)
      export TIMEDILATION="$2"
      shift 2
      ;;

    -h|--help)
      cat <<EOF
timedilation 0.1

Usage: timedilation [OPTIONS...] APPLICATION [ARGUMENTS...]

COMMANDS:
  -h, --help                      Show this help

OPTIONS:
  -n, --multiple                  Slow down time by this value multiple.
                                  It is recommended to use values with base 2
                                  because only that values can be used
                                  to precisely multiply and later divide back
                                  to the same integer number.
EOF
      exit 0
      ;;

    --)
      shift
      break
      ;;

    *)
      echo "Parsing failed! '$1'" >&2
      exit 1
      ;;

  esac

done

shift $(($OPTIND-1))

if [ x"$1" = x ] ; then
  echo "Please specify an application to profile!" >&2
  exit 1
fi

CURDIR=`realpath "$0"`
CURDIR=`dirname "$CURDIR"`

if [ x"$LD_PRELOAD" = x ] ; then
  export LD_PRELOAD="$CURDIR/libtimedilation.so"
else
  export LD_PRELOAD="$LD_PRELOAD:$CURDIR/libtimedilation.so"
fi

exec "$@"
